### ISSUE TITLE
Stellar job - proper well done

### ISSUE THREAD

**Issue by billabongbruno** [nerdynikhil/Acer-Nitro-5-AN515-52-593F-OpenCore-Hackintosh#1]
Greetings, fellow coder.
This is indeed a stellar job on your part. Everything is indeed running perfectly.
I would like to congratulate you on this.

I'm now running Catalina on my machine without a hitch thank to you.

I have to be honest, though. I did try to install Big Sur with your EFI folder and sadly it kept rebooting near the end of the installation.
Do you, by any chance, plan on uploading a Big Sur compatible version?
(Or are able to shed some light on what needs fixing, so I / others can do it?)

Best regards and once again, proper well done and THANK YOU.
You have no idea how many hours I have spent on this.

Cheers.

**Comment by nerdynikhil** [comment]
> Greetings, fellow coder.
> This is indeed a stellar job on your part. Everything is indeed running perfectly.
> I would like to congratulate you on this.
> 
> I'm now running Catalina on my machine without a hitch thank to you.
> 
> I have to be honest, though. I did try to install Big Sur with your EFI folder and sadly it kept rebooting near the end of the installation.
> Do you, by any chance, plan on uploading a Big Sur compatible version?
> (Or are able to shed some light on what needs fixing, so I / others can do it?)
> 
> Best regards and once again, proper well done and THANK YOU.
> You have no idea how many hours I have spent on this.
> 
> Cheers.

Glad that it helped you! But you need to change lil bit of stuff in your config.plist. Can you drop me an email on nerdynikhil@gmail.com? Thanks.

**Comment by billabongbruno** [comment]
> > Greetings, fellow coder.
> > This is indeed a stellar job on your part. Everything is indeed running perfectly.
> > I would like to congratulate you on this.
> > I'm now running Catalina on my machine without a hitch thank to you.
> > I have to be honest, though. I did try to install Big Sur with your EFI folder and sadly it kept rebooting near the end of the installation.
> > Do you, by any chance, plan on uploading a Big Sur compatible version?
> > (Or are able to shed some light on what needs fixing, so I / others can do it?)
> > Best regards and once again, proper well done and THANK YOU.
> > You have no idea how many hours I have spent on this.
> > Cheers.
> 
> Glad that it helped you! But you need to change lil bit of stuff in your config.plist. Can you drop me an email on [nerdynikhil@gmail.com](mailto:nerdynikhil@gmail.com)? Thanks.

Hello again.

Yes, your help was in fact invaluable.
I spent many hours trying to achieve a fully working system, but I never got it to work.
Only your EFI folder (which I have been looking at, so I can learn - config.plist and the kexts) have done it for me.

Thank you for your prompt reply and your availability.

I have sent you an e-mail, as per your suggestion.

Should be there by now. (santana.banva@gmail.com)

EDIT:
I now have a fully functioning BigSur 11.4 version, with only the dGPU disabled.
Everything else, including the headphone jack and card reader now works.
Boot time is amazing.

Thank you for your help, which ultimately led to this result.
